fix: check unique word to fetch question
KhalisFoundation/gurmukhi-web pull request #114
Opened 2024-02-25 13:32 UTC by MySmilingTurban

2024-02-28 20:01 UTC, amitojsingh commented
![Screenshot 2024-02-28 at 12 58 31 PM](https://github.com/KhalisFoundation/gurmukhi-web/assets/3595397/8402718a-8c44-46b1-818b-44dc09b1e9eb)
![Screenshot 2024-02-28 at 12 59 23 PM](https://github.com/KhalisFoundation/gurmukhi-web/assets/3595397/e356c725-1a86-4d14-8b8e-5f28260a06cc)

Veer ji I can still see the same questions twice

2024-03-08 03:09 UTC, amitojsingh requested changes

2024-03-08 03:09 UTC, amitojsingh commented on src/pages/dashboard/utils/index.ts
> +    console.log('learningWords', learningWords);
can we remove console?

2024-03-08 03:09 UTC, amitojsingh commented on src/pages/dashboard/utils/index.ts
> +  console.log('learntQuestions', learntQuestions);
remove console

2024-03-08 03:09 UTC, amitojsingh commented on src/pages/dashboard/utils/index.ts
> +  console.log('keysArray: ', keysArray);
remove console from line 72-74

2024-03-08 03:09 UTC, amitojsingh commented on src/pages/dashboard/utils/index.ts
> +    const { game, learningWords } = await getNewQuestions(13, user.uid, ['unknown'], true);
instead of ['unknown'] can we use any blank array [] or null value?

2024-03-08 03:09 UTC, amitojsingh commented on src/pages/dashboard/index.tsx
> +  useEffect(() => {
we can remove this

2024-03-08 03:09 UTC, amitojsingh commented on src/pages/dashboard/index.tsx
> +  useGamePlay(user, toggleLoading, user.uid && currentGamePosition === 0); // resetGame = true, resets the game on refresh or page change or after random word is viewed
Why are we resetting on refresh or page change? are we creating the gameArray again?

2024-03-08 23:21 UTC, amitojsingh commented
@MySmilingTurban Veer ji, while testing the app got hanged.

2024-03-09 00:06 UTC, MySmilingTurban commented
fix for this has been merged via #102

2024-03-15 22:48 UTC, MySmilingTurban commented
fixed in another PR

2024-03-15 22:48 UTC, closed without merging