fix: made responsive login/signup page
KhalisFoundation/gurmukhi-web pull request #115
Opened 2024-02-27 20:26 UTC by amitojsingh

2024-02-29 05:44 UTC, MySmilingTurban reviewed
We need to make some more change as here's how it looks on phone:

![login:signup-err1](https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/c99547f7-72a2-4490-aea0-4a6d8aba8ffd)

2024-02-29 05:44 UTC, MySmilingTurban commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-24 h-24 md:w-20 md:h-auto md:rounded-none rounded-full mx-auto absolute bottom-0 -left-10'
h-auto is stretching the gurfateh singh's picture, set w-auto too for that media query

2024-02-29 05:44 UTC, MySmilingTurban commented on src/components/modal/index.tsx
> +      <section className='absolute w-4/5 xl:w-1/3 border border-zinc-950 p-8 rounded-lg bg-white w-80% h-auto top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2'>
the form should scrollable in itself as it is showing up as the attached image
![login:signup-err2](https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/7d8246af-9e9b-416e-9c2b-e6c329351cd9)

2024-02-29 05:44 UTC, MySmilingTurban commented on src/styles/globals.scss
> +height: 100%;
nit: fix indentation

2024-02-29 05:44 UTC, MySmilingTurban commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-24 h-24 md:w-20 md:h-auto md:rounded-none rounded-full mx-auto absolute bottom-0 -left-10'
<img width="482" alt="Screenshot 2024-02-29 at 4 42 41 pm" src="https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/83067288-4ec2-4a64-8db5-b8d454010d7e">

2024-03-01 19:36 UTC, amitojsingh commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-24 h-24 md:w-20 md:h-auto md:rounded-none rounded-full mx-auto absolute bottom-0 -left-10'
fixed veerji

2024-03-01 19:37 UTC, amitojsingh commented on src/components/modal/index.tsx
> +      <section className='absolute w-4/5 xl:w-1/3 border border-zinc-950 p-8 rounded-lg bg-white w-80% h-auto top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2'>
fixed veer ji

2024-03-01 19:37 UTC, amitojsingh commented on src/styles/globals.scss
> +height: 100%;
fixed veer ji

2024-03-01 21:36 UTC, MySmilingTurban commented
Please fix the sign up/sign in form, as you can see in the video it has a lot of white space underneath the form elements

https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/7c10de47-a93b-4c3f-8717-0b6c0b904922

2024-03-01 21:42 UTC, MySmilingTurban commented
Also, please fix the responsiveness between width 1024 to 1280

https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/8206a87b-b771-455e-a2c2-c1ab7e5ef87c

2024-03-01 21:44 UTC, MySmilingTurban commented
Plus, for screen with width less than 450 we need to make sure that Gurfateh Singh doesn't cover up the text

https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/0137cd70-1d46-4306-8118-003b03f442f7

2024-03-01 22:26 UTC, amitojsingh commented
fixed @MySmilingTurban  veer ji please verify

2024-03-01 22:55 UTC, MySmilingTurban requested changes
minor changes requested

2024-03-01 22:55 UTC, MySmilingTurban commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-auto h-auto md:rounded-none rounded-full mx-auto absolute bottom-0 -left-10'
change bottom-0 to -bottom-1 to align gurfateh singh with text box

2024-03-01 23:25 UTC, amitojsingh commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-auto h-auto md:rounded-none rounded-full mx-auto absolute bottom-0 -left-10'
fixed

2024-03-01 23:28 UTC, amitojsingh commented on src/components/signin/SignIn.tsx
> +                className='w-full flex p-4 rounded-lg bg-transparent hover:bg-slate-100 text-black text-lg items-center justify-center gap-4 border border-gray-300'
fixed

2024-03-01 23:43 UTC, MySmilingTurban requested changes

2024-03-01 23:43 UTC, MySmilingTurban commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-auto h-auto md:rounded-none rounded-full mx-auto absolute -bottom-1 sm:bottom-0 -left-10'
why do we need sm:bottom-0 ??

2024-03-01 23:49 UTC, amitojsingh commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-auto h-auto md:rounded-none rounded-full mx-auto absolute -bottom-1 sm:bottom-0 -left-10'
veer ji as you said to change -bottom-1 for width ~365 I change and for rest of the sizes I changed to bottom-0
As you can see I have updated Gurfateh code alot so this according to that I have added bottom-0

2024-03-02 00:09 UTC, MySmilingTurban commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-auto h-auto md:rounded-none rounded-full mx-auto absolute -bottom-1 sm:bottom-0 -left-10'
please change it all to -bottom-1 as it still feels off when in media query covered by sm

<img width="823" alt="Screenshot 2024-03-02 at 11 08 38 am" src="https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/48d4b588-e82a-4a93-b2c3-20e9558c9d14">

2024-03-02 00:14 UTC, amitojsingh commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-auto h-auto md:rounded-none rounded-full mx-auto absolute -bottom-1 sm:bottom-0 -left-10'
done veer ji I changed all to bottom-0

2024-03-02 00:20 UTC, MySmilingTurban commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-auto h-auto md:rounded-none rounded-full mx-auto absolute -bottom-1 sm:bottom-0 -left-10'
veerji, -bottom-1 karna si saara

2024-03-02 00:20 UTC, MySmilingTurban commented on src/components/gurfateh/Gurfateh.tsx
> +            className='w-auto h-auto md:rounded-none rounded-full mx-auto absolute -bottom-1 sm:bottom-0 -left-10'
@amitojsingh

2024-03-02 00:45 UTC, MySmilingTurban approved these changes
Looks good to me!

2024-03-02 00:48 UTC, merged