Responsive Dashboard
KhalisFoundation/gurmukhi-web pull request #116
Opened 2024-02-28 00:13 UTC by amitojsingh

2024-03-01 21:47 UTC, MySmilingTurban commented
The words you learnt box collapses when width goes below 768

https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/87a95a49-dc8e-417f-af8e-b4b04b0f68da

2024-03-01 21:54 UTC, MySmilingTurban commented
Another thing, below 341 width, it squeezes the profile icon in the header
Also, make sure the background remains as parallax because right now I can see it repeat

https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/bf301324-a976-450a-bf2c-6acd600197e3

2024-03-01 23:40 UTC, amitojsingh commented
Fixed @MySmilingTurban  Veer ji can you try now.

2024-03-01 23:46 UTC, amitojsingh commented
@MySmilingTurban  Veer ji I changed the design because the text was getting overlapped with the header on scroll which is poor typography so to avoid that I have added a background to header and footer which is very much similar with minor difference.

2024-03-01 23:47 UTC, MySmilingTurban commented
Please don't add background image to header and footer, it messes up the design

https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/a59a8774-1b9d-40b9-bb8e-23e4c41d870f

2024-03-01 23:48 UTC, MySmilingTurban commented
Oh, can you can there background to blur instead of a solid picture, cuz it feels odd

2024-03-01 23:51 UTC, MySmilingTurban commented
you can remove background picture from footer, as it will not overlap any text as it is fixed to bottom of the page

2024-03-01 23:57 UTC, amitojsingh commented
fixed veer ji

2024-03-02 00:19 UTC, MySmilingTurban requested changes

2024-03-02 00:19 UTC, MySmilingTurban commented on src/components/questions/multiple-choice.tsx
> +        <h1 className={'xl:text-5xl text-4xl gurmukhi text-black font-semibold leading-snug'}>
nit: media query class name should be written after general ones

2024-03-02 00:19 UTC, MySmilingTurban commented on src/assets/icons/Shabadavali.tsx
> +    <div className='flex items-center justify-center md:w-12 md:h-12 w-5 h-5 mr-4 rounded-full logo-bg'>
media query class name should be written after general ones

2024-03-02 00:19 UTC, MySmilingTurban commented on src/pages/dashboard/components/coinbox/index.tsx
> +        <div className=''>
nit: remove empty classname

2024-03-02 00:19 UTC, MySmilingTurban commented on src/pages/wincoin/index.tsx
> +        <div className=' mx-auto bg-cyan-50 xl:w-1/4 w-2/4 rounded-xl'>
nit: media query class name should be written after general ones

2024-03-02 00:19 UTC, MySmilingTurban commented on src/pages/word/information/index.tsx
> +      <div className='flex flex-col h-3/4 justify-between items-center '>
nit: empty space

2024-03-02 00:19 UTC, MySmilingTurban commented on src/pages/word/information/index.tsx
> +          <div className='flex flex-col items-left justify-evenly xl:w-1/2 w-3/4 h-full'>
nit: media query class name should be written after general ones

2024-03-02 00:19 UTC, MySmilingTurban commented on src/pages/word/information/index.tsx
> +                className={`lg:w-2/5 w-5/6 h-full cardImage bg-cover bg-sky-100 bg-blend-soft-light hover:bg-sky-50 border-2 border-sky-200 shadow-lg rounded-lg ${
nit: media query class name should be written after general ones

2024-03-02 00:19 UTC, MySmilingTurban commented on src/pages/word/information/index.tsx
> +                className={`lg:w-2/5 w-5/6 h-full cardImage bg-cover bg-sky-100 bg-blend-soft-light hover:bg-sky-50 border-2 border-sky-200 shadow-lg rounded-lg ${
nit: media query class name should be written after general ones

2024-03-02 00:19 UTC, MySmilingTurban commented on src/styles/globals.scss
> +.back-bg-image {
nit: add empty line after each class style

2024-03-02 00:30 UTC, amitojsingh commented on src/components/questions/multiple-choice.tsx
> +        <h1 className={'xl:text-5xl text-4xl gurmukhi text-black font-semibold leading-snug'}>
fixed

2024-03-02 00:30 UTC, amitojsingh commented on src/assets/icons/Shabadavali.tsx
> +    <div className='flex items-center justify-center md:w-12 md:h-12 w-5 h-5 mr-4 rounded-full logo-bg'>
fixed

2024-03-02 00:30 UTC, amitojsingh commented on src/pages/dashboard/components/coinbox/index.tsx
> +        <div className=''>
fixed

2024-03-02 00:30 UTC, amitojsingh commented on src/pages/wincoin/index.tsx
> +        <div className=' mx-auto bg-cyan-50 xl:w-1/4 w-2/4 rounded-xl'>
fixed

2024-03-02 00:30 UTC, amitojsingh commented on src/pages/word/information/index.tsx
> +      <div className='flex flex-col h-3/4 justify-between items-center '>
fixed

2024-03-02 00:30 UTC, amitojsingh commented on src/pages/word/information/index.tsx
> +          <div className='flex flex-col items-left justify-evenly xl:w-1/2 w-3/4 h-full'>
fixed

2024-03-02 00:30 UTC, amitojsingh commented on src/pages/word/information/index.tsx
> +                className={`lg:w-2/5 w-5/6 h-full cardImage bg-cover bg-sky-100 bg-blend-soft-light hover:bg-sky-50 border-2 border-sky-200 shadow-lg rounded-lg ${
fixed

2024-03-02 00:30 UTC, amitojsingh commented on src/pages/word/information/index.tsx
> +                className={`lg:w-2/5 w-5/6 h-full cardImage bg-cover bg-sky-100 bg-blend-soft-light hover:bg-sky-50 border-2 border-sky-200 shadow-lg rounded-lg ${
fixed

2024-03-02 00:31 UTC, amitojsingh commented on src/styles/globals.scss
> +.back-bg-image {
fixed

2024-03-02 00:49 UTC, MySmilingTurban requested changes

2024-03-02 00:49 UTC, MySmilingTurban commented on src/assets/icons/Shabadavali.tsx
> +    <div className='flex items-center justify-center w-5 h-5 mr-4 rounded-full logo-bg md:w-12 md:h-12 '>
nit: remove empty space in end of classname

2024-03-02 00:49 UTC, MySmilingTurban commented on src/components/questions/multiple-choice.tsx
> +        <h1 className={' gurmukhi text-black font-semibold leading-snug xl:text-5xl text-4xl'}>
change the classname to 
`gurmukhi text-black font-semibold leading-snug text-4xl xl:text-5xl`
(remove empty space and order of media query)

2024-03-02 00:58 UTC, amitojsingh commented on src/assets/icons/Shabadavali.tsx
> +    <div className='flex items-center justify-center w-5 h-5 mr-4 rounded-full logo-bg md:w-12 md:h-12 '>
fixed

2024-03-02 00:58 UTC, amitojsingh commented on src/components/questions/multiple-choice.tsx
> +        <h1 className={' gurmukhi text-black font-semibold leading-snug xl:text-5xl text-4xl'}>
fixed

2024-03-02 06:52 UTC, MySmilingTurban commented
Please fix the image pages for word

<img width="769" alt="Screenshot 2024-03-02 at 5 51 55 pm" src="https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/93e173d6-aec0-46fd-b632-4449354a942a">

2024-03-08 23:19 UTC, amitojsingh commented
@MySmilingTurban veer ji looks like you have zoomed in on the image can you verify with 100% zoom?

2024-03-09 16:33 UTC, amitojsingh commented
@MySmilingTurban Veer ji please review

2024-03-09 23:25 UTC, MySmilingTurban requested changes
Looks good to me!
One minor issue with the highlighted element in the attached screenshot, can we make it responsive too

<img width="438" alt="Screenshot 2024-03-10 at 10 20 23 am" src="https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/ca028bf5-f669-477a-b0e8-1ccd9bcc4a89">

2024-03-10 04:21 UTC, amitojsingh commented
fixed veer ji @MySmilingTurban

2024-03-10 04:34 UTC, MySmilingTurban approved these changes
Looks good to me!

2024-03-10 05:12 UTC, merged