fix: inder Veer ji bug
KhalisFoundation/gurmukhi-web pull request #143
Opened 2024-04-06 23:45 UTC by amitojsingh

2024-04-19 03:03 UTC, MySmilingTurban requested changes

2024-04-19 03:03 UTC, MySmilingTurban commented on src/pages/profile/index.tsx
> +      setVerifiable(!(user?.emailVerified ?? true));
should we change these 
`user?.displayName ?? ''`
to
`user?.displayName || ''`

2024-04-19 22:32 UTC, amitojsingh commented on src/components/signin/LogOut.tsx
>        }
fixed

2024-04-19 22:32 UTC, amitojsingh commented on src/components/signin/SignIn.tsx
> +
fixed

2024-04-19 22:32 UTC, amitojsingh commented on src/components/signin/SignIn.tsx
> +      console.warn('Switch element not found.');
fixed

2024-04-19 22:32 UTC, amitojsingh commented on src/pages/dashboard/hooks/useGamePlay1.ts
>            toggleLoading(false);
fixed

2024-04-19 22:32 UTC, amitojsingh commented on src/pages/profile/index.tsx
> +      setVerifiable(!(user?.emailVerified ?? true));
fixed

2024-04-20 00:14 UTC, MySmilingTurban requested changes

2024-04-22 08:21 UTC, MySmilingTurban commented
@amitojsingh veerji, do have a final look before merging it

2024-04-22 18:52 UTC, merged