fix: responsive designing
KhalisFoundation/gurmukhi-web pull request #169
Opened 2024-04-26 03:04 UTC by amitojsingh

2024-05-02 04:43 UTC, MySmilingTurban commented on src/components/gurfateh/Gurfateh.tsx
> -          <h1 className='text-xl font-medium text-black text-left gurmukhi'>
gurmukhi classname is needed to apply our chosen font for Gurmukhi text

2024-05-02 04:43 UTC, MySmilingTurban commented on src/components/ssa/index.tsx
> +        <span className='cormont-garamond-light capitalize'>
we should discuss this in a meeting with Inder Singh Veerji to see which font suits well
(I love how this new font adds more flavour to the app)

2024-05-29 00:07 UTC, amitojsingh commented on src/components/gurfateh/Gurfateh.tsx
> -          <h1 className='text-xl font-medium text-black text-left gurmukhi'>
fixed

2024-05-29 00:07 UTC, amitojsingh commented on src/components/ssa/index.tsx
> +        <span className='cormont-garamond-light capitalize'>
fixed

2024-05-29 02:29 UTC, MySmilingTurban requested changes
all looks good, just remove the import statement of the font not in use anymore

2024-05-29 02:29 UTC, MySmilingTurban commented on src/styles/globals.scss
>  @font-face {
nit: remove redundant font

2024-05-31 00:49 UTC, MySmilingTurban commented on src/styles/globals.scss
>  @font-face {
fixed

2024-05-31 00:56 UTC, MySmilingTurban approved these changes
Looks good to me!

2024-05-31 03:21 UTC, merged