feat: added tests
KhalisFoundation/gurmukhi-web pull request #199
Opened 2024-06-18 00:10 UTC by amitojsingh

2024-06-18 22:44 UTC, MySmilingTurban requested changes
one minor fix requested

2024-06-18 22:44 UTC, MySmilingTurban commented on src/components/ssa/ssa.test.tsx
> +describe('Ssa component', () => {
nit: add empty line

2024-06-18 22:46 UTC, MySmilingTurban commented
@amitojsingh veerji, shouldn't all test be in single folder named tests?

2024-06-19 20:13 UTC, amitojsingh commented
@MySmilingTurban veer ji It's considered best practice to store unit test files adjacent to their corresponding source code files. This arrangement simplifies locating the relevant tests for each component of the application.

2024-06-22 10:46 UTC, MySmilingTurban approved these changes
Looks good to me!

2024-06-22 10:46 UTC, merged