Bug fixes
KhalisFoundation/gurmukhi-web pull request #203
Opened 2024-07-08 05:44 UTC by MySmilingTurban

Fixes issues with sign in with google and saving state with end session button.

2024-07-09 19:11 UTC, amitojsingh requested changes

2024-07-09 19:11 UTC, amitojsingh commented on src/auth/index.tsx
> +        console.log('UserDetails2inHook', userDetails);
can we remove this console?

2024-07-09 19:11 UTC, amitojsingh commented on src/components/buttons/EndSessionBtn.tsx
> +    console.log('Current Data: ', currentData);
console

2024-07-09 19:11 UTC, amitojsingh commented on src/database/shabadavalidb/words.ts
> +    console.log('querySnapshot:', querySnapshot);
console

2024-07-09 19:11 UTC, amitojsingh commented on src/database/shabadavalidb/words.ts
> +    console.log('querySnapshot:', querySnapshot);
in the whole page.

2024-07-09 19:45 UTC, amitojsingh commented on src/auth/index.tsx
> +        dispatch(setCurrentGamePosition(userData.progress.currentProgress));
don't thing veer ji we should add this in useEffect.

2024-07-10 01:31 UTC, MySmilingTurban commented on src/auth/index.tsx
> +        dispatch(setCurrentGamePosition(userData.progress.currentProgress));
I just tested it after removing the part from useEffect, it doesn't work.
But when I removed it from signInWithGoogle function but not from useEffect it works.

2024-08-09 07:37 UTC, gurjit03 commented on src/auth/index.tsx
> +            user: null as FirebaseUser | null,
@MySmilingTurban Any chance we can avoid this `typecasting` as well? 
https://medium.com/livefront/to-cast-or-not-to-cast-a-typescript-dilemma-c0c20c53c6d9

2024-08-09 07:37 UTC, gurjit03 commented on src/auth/index.tsx
> +        console.log('UserDetails2inHook', userDetails);
@MySmilingTurban stale log here !

2024-08-09 07:37 UTC, gurjit03 commented on src/auth/index.tsx
> +        dispatch(addNextScreens(userData.nextSession ?? []));
@MySmilingTurban Can see too many dispatch calls and also similar calls below, just was wondering can we combine those ?

2024-08-11 03:41 UTC, closed without merging