Removed unnecessary getUserData calls and added userData in redux state for backup
KhalisFoundation/gurmukhi-web pull request #224
Opened 2024-07-13 13:49 UTC by MySmilingTurban

2024-07-14 15:53 UTC, amitojsingh requested changes

2024-07-14 15:53 UTC, amitojsingh commented on src/auth/index.tsx
> +        dispatch(setUserData(usr));
We are currently storing user data in two separate instances:

1. setUser(user)
2. dispatch(setUserData(usr))

To eliminate redundancy and confusion, I would like to consolidate these operations. Can we unify them into a single approach, either using the dispatch state method or the setUser state method?

2024-07-14 15:53 UTC, amitojsingh commented on src/pages/wincoin/index.tsx
> +  if (!user && userData !== undefined && userData.uid) user = userData;
Is it possible to synchronize the userDataState in our application whenever we update the user document in the database? This would ensure that our application's state consistently reflects the data stored in the database.

2024-07-14 15:53 UTC, amitojsingh commented on src/pages/wincoin/index.tsx
> +  if (!user && userData !== undefined && userData.uid) user = userData;
Also veer ji can we make sure the user Object is empty when the user logout?

2024-07-16 23:49 UTC, amitojsingh requested changes

2024-07-16 23:49 UTC, amitojsingh commented on src/pages/dashboard/index.tsx
> +            <Ssa name={user.displayName} />
why are we using && here?

2024-07-16 23:56 UTC, MySmilingTurban commented on src/pages/dashboard/index.tsx
> +            <Ssa name={user.displayName} />
we are not using it anymore ji, initially it was due uncertainity of existence of data in user but now it is the only source so no and anymore

2024-07-17 00:01 UTC, amitojsingh commented on src/pages/dashboard/index.tsx
> +            <Ssa name={user.displayName} />
Oh! My mistake I compared the wrong side.

2024-07-17 00:01 UTC, amitojsingh commented
Just fix the Deep scan and we are good to merge.

2024-07-17 00:13 UTC, amitojsingh approved these changes

2024-07-18 02:38 UTC, amitojsingh requested changes

2024-07-18 02:38 UTC, amitojsingh commented on src/auth/index.tsx
> +    console.log('next session from user: ', userDetails.nextSession);
remove console.

2024-07-18 02:42 UTC, amitojsingh approved these changes

2024-07-18 02:44 UTC, merged