fix: profile page
KhalisFoundation/gurmukhi-web pull request #235
Opened 2024-07-18 22:20 UTC by amitojsingh

2024-07-20 02:44 UTC, Gauravjeetsingh requested changes
@amitojsingh veerji, I am unable to sign in with google with the deployment of this PR, can you please check.

2024-07-20 13:18 UTC, MySmilingTurban commented
> @amitojsingh veerji, I am unable to sign in with google with the deployment of this PR, can you please check.

@Gauravjeetsingh veerji, can you try if it works on local?
Due to some reason the deployments on PR doesn't work well with logins because auth only has the main dev and prod URLs allowed in it but these live channels are not added automatically.

2024-07-21 08:22 UTC, MySmilingTurban commented
Tested this on local, it is not working as intended.
Will post some fixes for it.

2024-07-22 05:02 UTC, MySmilingTurban commented
adding fix to this error which was avoiding saving of name in my case
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/ae7b3e7e-ecb3-43a4-befa-1589c977633e">

2024-07-22 08:10 UTC, MySmilingTurban commented
@Gauravjeetsingh and @amitojsingh Veerjis,
Please test this on local and review the code whenever possible.
The above changes were made based on the problems I faced while testing this use case.

2024-07-22 21:17 UTC, amitojsingh commented
@MySmilingTurban Veer ji can you update the description and point out the issues we solved in this PR.

2024-07-23 01:56 UTC, Gauravjeetsingh requested changes
Need context on the changes we have in this PR related to profile verification functionality.

2024-07-23 01:56 UTC, Gauravjeetsingh commented on src/pages/profile/components/EmailVerification.tsx
Is this intentional change to push this file, or pushed by mistake. Not sure if we need this code for the profile page fix?

2024-07-23 02:04 UTC, amitojsingh commented on src/pages/profile/components/EmailVerification.tsx
We can comment for now. I just restructured the profile/index.tsx file and made small components to make it more readable and structured.

2024-07-23 02:31 UTC, MySmilingTurban requested changes
minor changes, working on them rn

2024-07-23 02:31 UTC, MySmilingTurban commented on src/constants/constant.ts
>    DATA_LIMIT: 3,
remove unused constants

2024-07-23 02:31 UTC, MySmilingTurban commented on src/utils/utils.ts
>  };
convert to export default

2024-07-23 02:31 UTC, MySmilingTurban commented on src/pages/wincoin/index.tsx
> +import { convertNumber } from 'utils/utils';
import as default

2024-07-23 02:31 UTC, MySmilingTurban commented on src/pages/profile/index.tsx
> +    dispatch(setUserData({ ...user, ...updatedUserData }));
avoid update all data in user, instead update a part and take rest from state in userDataSlice

2024-07-23 02:51 UTC, MySmilingTurban commented on src/pages/profile/components/EmailVerification.tsx
Commented email verification option for now and created new task to track reset password functionality which uses email verification.

2024-07-26 23:42 UTC, amitojsingh commented on src/types/shabadavalidb.ts
> +export interface PartialUser {
why all the fields are optional?

2024-07-26 23:44 UTC, MySmilingTurban commented on src/types/shabadavalidb.ts
> +export interface PartialUser {
because it is used in updateUser, where not all fields are necessary to be passed.
We can pass any fields and code will take the rest from the redux state itself

2024-07-27 01:19 UTC, amitojsingh commented on src/types/shabadavalidb.ts
> +export interface PartialUser {
Okay, veer ji makes sense.

2024-07-27 01:20 UTC, amitojsingh commented on src/types/shabadavalidb.ts
> +  created_at?: Timestamp | string;
can we update this as well?

2024-07-28 20:24 UTC, amitojsingh commented
Profile image saved using sign In with Google is not retained.

2024-07-28 20:31 UTC, amitojsingh commented on src/types/shabadavalidb.ts
> +  created_at?: Timestamp | string;
fixed

2024-07-28 20:33 UTC, amitojsingh commented
@Gauravjeetsingh @MySmilingTurban Veer ji Please review/ test and merge.

2024-07-29 11:24 UTC, MySmilingTurban approved these changes
Looks good to me!

2024-07-30 05:19 UTC, gurjit03 requested changes

2024-07-30 05:19 UTC, gurjit03 commented on src/pages/profile/components/EmailVerification.tsx
> +// Commented because not essential at the moment, will be used for Reset Password feature
@MySmilingTurban We can safely remove this commented code/infact file as per say.
https://methodpoet.com/commented-out-code/

2024-07-30 05:19 UTC, gurjit03 commented on src/pages/profile/components/GetTabData.tsx
> +const getTabData = (heading: string, info: string, editMode: boolean, children?: JSX.Element) => {
@MySmilingTurban we shouldn't need to type children, we can directly use it through the props.

2024-07-30 05:19 UTC, gurjit03 commented on src/pages/profile/components/RenderButton.tsx
> +const renderButton = (
@MySmilingTurban we can improve this to follow react standards making it with capital letters. Easy to stick to standards for consistency ;)

2024-07-30 05:19 UTC, gurjit03 commented on src/pages/profile/components/RenderButton.tsx
> +  textValue: string,
@MySmilingTurban NIT: It's not a value so better alternative can be `text` or `children`!

2024-07-30 05:19 UTC, gurjit03 commented on src/pages/profile/index.tsx
> +  const buttonSelector = () => {
@MySmilingTurban I would recommend choosing the route of declarative programming rather than imperative. Much easier to understand and less code !
For eg
```
<RenderButton text={editMode ? 'edit' : 'save'} onClick={editMode ? handleEditMode : handleSave}  /> 
```

Rest of the props should be optional and have `false` value by default.

2024-07-30 05:21 UTC, gurjit03 commented on src/pages/profile/index.tsx
> +  const buttonSelector = () => {
Now thinking futher I would go one step ahead, can go in seperate PR obv and try to achieve the following 

```
<Button variant="primary, secondary ...." text="xyz" onClick={() => {}) />
```

2024-08-01 04:19 UTC, MySmilingTurban commented on src/pages/profile/components/EmailVerification.tsx
> +// Commented because not essential at the moment, will be used for Reset Password feature
removed

2024-08-01 06:43 UTC, MySmilingTurban commented on src/pages/profile/components/RenderButton.tsx
> +  textValue: string,
fixed

2024-08-01 06:44 UTC, MySmilingTurban commented on src/pages/profile/components/RenderButton.tsx
> +const renderButton = (
fixed

2024-08-01 13:45 UTC, MySmilingTurban commented on src/pages/profile/components/GetTabData.tsx
> +const getTabData = (heading: string, info: string, editMode: boolean, children?: JSX.Element) => {
fixed

2024-08-01 16:33 UTC, gurjit03 approved these changes
There are still components where we are typing the children.

2024-08-01 16:33 UTC, gurjit03 commented on src/pages/profile/components/TabData.tsx
> +  children?: ReactNode;
@MySmilingTurban we don't needs to type children !

2024-08-02 03:45 UTC, gurjit03 approved these changes

2024-08-02 06:02 UTC, merged