Migrate from NextJS to ReactJS
KhalisFoundation/gurmukhi-web pull request #24
Opened 2023-11-27 03:32 UTC by MySmilingTurban

2023-12-02 20:29 UTC, lbk003 commented
@MySmilingTurban - can you please capture the problems in the PR w/ the firebase deploy ?

2023-12-02 20:33 UTC, MySmilingTurban commented
> @MySmilingTurban - can you please capture the problems in the PR w/ the firebase deploy ?

As we can see, the action works smoothly on pull request and it also gives us a preview channel URL. Unfortunately, if we navigate to that link, it shows Firebase site not found.

I tried deploying the same to the default site, i.e., gurmukhi-dev, and it works fine.
I am looking into documentations as it seems like an internal issue because ideally if I am specifying the target site for deployment, it should be there on deployment.

2023-12-02 20:41 UTC, MySmilingTurban commented on firebase.json
> +    "target": "default",
our problem mostly revolves around [this](https://firebase.google.com/docs/hosting/multisites#set_up_deploy_targets)

2023-12-02 21:27 UTC, lbk003 requested changes

2023-12-02 21:27 UTC, lbk003 commented on .github/workflows/firebase-hosting-merge.yml
Remove this from this PR. Lets get hosting working first

2023-12-02 21:27 UTC, lbk003 commented on .github/workflows/firebase-hosting-pull-request.yml
Also, remove this file. We will add it back later once we have deploy working

2023-12-03 02:45 UTC, MySmilingTurban commented on firestore.rules
> +      allow read, write: if request.auth != null;
Firestore is working fine

2023-12-03 05:48 UTC, MySmilingTurban commented on src/constants/wordsData.ts
> +        sentenceEnglish: 'Gurvinder and I go to the ring every day to practice wrestling.',
Hnji, will be adding it after static web pages setup

2023-12-04 16:53 UTC, amitojsingh requested changes

2023-12-04 16:53 UTC, amitojsingh commented on firebase.json
> +    "target": "default",
@MySmilingTurban  is it fixed veer ji?

2023-12-04 16:53 UTC, amitojsingh commented on public/404.html
> +      body { background: #ECEFF1; color: rgba(0,0,0,0.87); font-family: Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; }
Veer ji can we use an external stylesheet here?

2023-12-04 16:53 UTC, amitojsingh commented on tsconfig.json
>      ".next/types/**/*.ts",
Veer ji, I belive we don't need this line.

2023-12-13 05:47 UTC, amitojsingh approved these changes

2023-12-13 06:51 UTC, merged