Bug unclickable space in options
KhalisFoundation/gurmukhi-web pull request #251
Opened 2024-07-24 14:14 UTC by MySmilingTurban

2024-07-25 03:36 UTC, amitojsingh commented
@MySmilingTurban Veer ji It's not good practice to add a button inside a button.

2024-07-25 03:47 UTC, amitojsingh requested changes

2024-07-25 03:47 UTC, amitojsingh commented on src/components/buttons/Option.tsx
> +      <button
@MySmilingTurban Veer ji It's not good practice to add a button inside a button.

2024-07-25 05:32 UTC, MySmilingTurban commented on src/components/buttons/Option.tsx
> +      <button
do you mean div inside a button veerji?

2024-07-26 23:37 UTC, amitojsingh commented on src/components/buttons/Option.tsx
> +      <button
nopes veer ji text to speach button inside button.

2024-07-28 13:40 UTC, MySmilingTurban commented on src/components/buttons/Option.tsx
> +      <button
fixed veerji

2024-07-28 19:31 UTC, amitojsingh approved these changes
LGTM

2024-07-28 19:31 UTC, merged