Fix: Profile page toDate bug on Firestore time object
KhalisFoundation/gurmukhi-web pull request #252
Opened 2024-07-24 19:38 UTC by MySmilingTurban

2024-07-24 19:51 UTC, amitojsingh commented
@MySmilingTurban Veer Ji Why we have multiple formats of date? can we use single format either timestamp or string?

2024-07-25 01:17 UTC, MySmilingTurban commented
> @MySmilingTurban Veer Ji Why we have multiple formats of date? can we use single format either timestamp or string?

It was there to handle inconsistent past data, added fix in migration script too. There were very few old documents that had this error.

2024-07-25 03:44 UTC, amitojsingh commented
@MySmilingTurban Veer ji can we create a new document for the script? instead of updating the existing document?

2024-07-25 03:46 UTC, amitojsingh requested changes

2024-07-25 03:46 UTC, amitojsingh commented on scripts/migrationExistingGoogleUsers.js
> +const { getFirestore, Timestamp } = require('firebase-admin/firestore');
@MySmilingTurban Veer ji can we make a new Document for the script? instead of updating the existing one.

2024-07-25 05:33 UTC, MySmilingTurban commented on scripts/migrationExistingGoogleUsers.js
> +const { getFirestore, Timestamp } = require('firebase-admin/firestore');
ok ji

2024-07-26 23:49 UTC, MySmilingTurban commented on scripts/migrationExistingGoogleUsers.js
> +const { getFirestore, Timestamp } = require('firebase-admin/firestore');
Some changes were needed in the condition when checking existence of lastLoginAtTime and formatting its value.
With my recent commit, I have removed created_at

2024-07-27 00:09 UTC, amitojsingh approved these changes
LGTM

2024-07-27 14:12 UTC, merged