Move to Production Profile Page Fixes
KhalisFoundation/gurmukhi-web pull request #261
Opened 2024-08-09 15:33 UTC by amitojsingh

2024-08-11 01:16 UTC, MySmilingTurban approved these changes
Looks good to me!

2024-08-11 08:35 UTC, gurjit03 requested changes
Great work @amitojsingh 🔥  some minor comments :)

2024-08-11 08:35 UTC, gurjit03 commented on src/components/buttons/TextToSpeechBtn.tsx
> +    console.log(text, type, audioURL, id, classname, rounded, backgroundColor, divider, setLoading, size);
@amitojsingh stale log

2024-08-11 08:35 UTC, gurjit03 commented on src/components/buttons/TextToSpeechBtn.tsx
> +//   classname = '',
@amitojsingh commented code

2024-08-11 08:35 UTC, gurjit03 commented on src/components/buttons/tests/OpenFeedbackBtn.test.tsx
>  jest.mock('components/feedback', () => {
@amitojsingh just wondering, why we need to mock this component here ?

2024-08-11 08:35 UTC, gurjit03 commented on src/components/buttons/tests/OpenFeedbackBtn.test.tsx
> +  const MockModal = ({ children }: PropsWithChildren) => (
@amitojsingh should we include tests to make sure the feedback is submitted correctly with correct arguments also ?

2024-08-11 08:35 UTC, gurjit03 commented on src/components/buttons/tests/option.test.tsx
> +    expect(screen.getByRole('button').parentElement).toHaveClass('bg-lightGreen');
@amitojsingh I highly recommend using other selector than `parentElement/parentNode` for getting element ji.

2024-08-11 08:35 UTC, gurjit03 commented on src/utils/storage.tsx
> +export const uploadImage = async (file: File, currentUser: User, setLoading: Dispatch<boolean>) => {
@amitojsingh lets remove all the side effects out of this function as it's not this function responsibility to handle the loading. Clearly this function is for uploading the Image. Loading indicator should be handled in the caller.

2024-08-12 00:37 UTC, amitojsingh commented
@gurjit03 Veer ji, I'll create a separate PR for the enhancements you suggested and we will merge in the next Release. It's not best practice to push code directly to the main branch. Currently, regression testing is underway. Should we ensure all functionalities in this PR are tested before merging to prod? If we merge additional code into this PR, it could invalidate the testing already completed by everyone.

2024-08-12 06:20 UTC, gurjit03 commented
> @gurjit03 Veer ji, I'll create a separate PR for the enhancements you suggested and we will merge in the next Release. It's not best practice to push code directly to the main branch. Currently, regression testing is underway. Should we ensure all functionalities in this PR are tested before merging to prod? If we merge additional code into this PR, it could invalidate the testing already completed by everyone.

@amitojsingh yes definitely !

2024-08-12 06:23 UTC, gurjit03 approved these changes

2024-08-14 00:37 UTC, merged