Create multiple choice questions page
KhalisFoundation/gurmukhi-web pull request #29
Opened 2023-12-13 07:25 UTC by MySmilingTurban

2023-12-15 06:10 UTC, amitojsingh commented
Please update the description I can see lots of commits.

2023-12-16 00:39 UTC, amitojsingh requested changes

2023-12-16 00:39 UTC, amitojsingh commented on src/components/buttons/StartQuestionBtn.tsx
> +        className='bg-[#D6E9F3] text-[#255C7A] rounded-lg p-3 w-52 text-center'
Veer ji can we make these colors somehow reusable? like defining colors in global.scss or color constants.

2023-12-16 01:25 UTC, MySmilingTurban commented on src/components/buttons/StartQuestionBtn.tsx
> +        className='bg-[#D6E9F3] text-[#255C7A] rounded-lg p-3 w-52 text-center'
fixed veerji

2023-12-16 01:27 UTC, amitojsingh approved these changes

2023-12-16 01:29 UTC, merged