feat: meta data and favicon
KhalisFoundation/gurmukhi-web pull request #41
Opened 2023-12-16 18:45 UTC by amitojsingh

2023-12-16 23:25 UTC, MySmilingTurban commented
@amitojsingh veerji, would it be possible to make the favicon a little bigger?
maybe remove the white border and make the letter bigger so it is readable.

2023-12-16 23:48 UTC, amitojsingh commented
Sure veer ji I can try

2023-12-16 23:51 UTC, MySmilingTurban requested changes

2023-12-16 23:51 UTC, MySmilingTurban commented on src/pages/word/semantics/index.tsx
> +  const { title, description } = metaTags.SEMANTICS;
move const definition before return
ideally any definition or functions should be before any return statement (got into a similar warning last week)
simply move it above the following code
```
if (!currentWord.word) {
    // Handle case when word is not found
    return <div>{text('WORD_NOT_FOUND')}</div>;
}
```

2023-12-16 23:51 UTC, MySmilingTurban commented on src/pages/word/information/index.tsx
> +  const { title, description } = metaTags.INFORMATION;
move const definition before conditional return statement

2023-12-16 23:51 UTC, MySmilingTurban commented on src/pages/word/information/index.tsx
>      return <div>{text('WORD_NOT_FOUND')}</div>;
Should we add a redirect to the "word not found" page (needs to be created) instead?
would also need metadata for that specific page.
please create an issue for this if needed

2023-12-16 23:51 UTC, MySmilingTurban commented on src/pages/word/layout.tsx
> +  const { title, description } = metaTags.WORD;
This metadata will be overwritten by the respective pages (word/definition, examples, semantics, information), as this acts as a common layout for them.

2023-12-16 23:51 UTC, MySmilingTurban commented on src/pages/word/examples/index.tsx
> +  const { title, description } = metaTags.EXAMPLES;
best position!
can we move all these metadata definitions to this position in every file, like 2-3 lines after function definition?
(to make code more readable)

2023-12-16 23:51 UTC, MySmilingTurban commented on src/pages/questions/index.tsx
> +  const { title, description } = metaTags.QUESTION;
refer to metadata comment and change accordingly

2023-12-16 23:51 UTC, MySmilingTurban commented on src/pages/layout.tsx
>      <html lang='en'>
do we still need html tag?

2023-12-17 02:31 UTC, amitojsingh commented on src/pages/word/information/index.tsx
>      return <div>{text('WORD_NOT_FOUND')}</div>;
I think for now we can redirect to 404 not found. what do you think?

2023-12-17 02:32 UTC, amitojsingh commented on src/pages/word/semantics/index.tsx
> +  const { title, description } = metaTags.SEMANTICS;
fixed veer ji

2023-12-17 03:23 UTC, amitojsingh commented on src/pages/word/examples/index.tsx
> +  const { title, description } = metaTags.EXAMPLES;
okay veer ji

2023-12-17 03:23 UTC, amitojsingh commented on src/pages/layout.tsx
>      <html lang='en'>
no I removed it

2023-12-17 03:23 UTC, amitojsingh commented on src/pages/questions/index.tsx
> +  const { title, description } = metaTags.QUESTION;
done veer ji

2023-12-17 03:23 UTC, amitojsingh commented on src/pages/word/layout.tsx
> +  const { title, description } = metaTags.WORD;
removed veer ji

2023-12-17 03:24 UTC, amitojsingh commented on src/pages/word/information/index.tsx
> +  const { title, description } = metaTags.INFORMATION;
done veer ji

2023-12-17 03:24 UTC, amitojsingh commented
@MySmilingTurban Veer ji I have updated the favicon.

2023-12-17 03:29 UTC, MySmilingTurban commented on src/pages/word/information/index.tsx
>      return <div>{text('WORD_NOT_FOUND')}</div>;
ya, sounds good

2023-12-17 03:33 UTC, MySmilingTurban approved these changes
looks good to me!

2023-12-17 03:33 UTC, merged