feat: add indication for number of synonyms/antonyms left
KhalisFoundation/gurmukhi-web pull request #42
Opened 2023-12-17 07:05 UTC by MySmilingTurban

adds indication for number of synonyms or antonyms left
plus confetti and toast to indicate completion of semantics task

2023-12-18 18:17 UTC, amitojsingh requested changes

2023-12-18 18:17 UTC, amitojsingh commented on src/pages/word/semantics/index.tsx
> +    toast.success(text('SEMANTICS_PRAISE'), {
Do we need toast veer ji? I can see toast is covering the next button. Although, confetti is quite good.

2023-12-18 18:17 UTC, amitojsingh commented on src/pages/word/semantics/index.tsx
>            </div>
The file is getting too big is it possible if we can divide code in subcomponents/utils/custom hooks?

2023-12-28 04:18 UTC, MySmilingTurban commented on src/pages/word/semantics/index.tsx
> +    toast.success(text('SEMANTICS_PRAISE'), {
Veerji, I have moved the position of toast to top center, so it doesn't cover any existing items. I think it gives some positive reinforcement that you are on track and what's coming next.

2023-12-28 04:48 UTC, MySmilingTurban commented on src/pages/word/semantics/index.tsx
>            </div>
fixed

2023-12-28 05:27 UTC, amitojsingh approved these changes

2023-12-28 06:59 UTC, merged