fix: basic gameplay, designing fix
KhalisFoundation/gurmukhi-web pull request #61
Opened 2024-01-11 05:14 UTC by amitojsingh

2024-01-13 06:07 UTC, MySmilingTurban requested changes

2024-01-15 18:08 UTC, amitojsingh commented on src/store/features/currentGamePositionSlice.ts
> +  currentGamePositionSlice.actions;
updated

2024-01-15 18:08 UTC, amitojsingh commented on src/utils/gamePlay.ts
> +          gameArray.push(`${ALL_CONSTANT.DEFINATION}-${word.id}`);
fixed

2024-01-16 00:30 UTC, MySmilingTurban requested changes
Thanks for the fixes.
Some minor changes requested

2024-01-16 00:30 UTC, MySmilingTurban commented on src/store/features/currentGamePositionSlice.ts
> +const currentGamePositionSlice = createSlice({
nit: add empty line after import

2024-01-16 00:30 UTC, MySmilingTurban commented on src/components/buttons/StartQuestionBtn.tsx
>        <button
button as a descendant of anchor tag is not considered best practice, can we change the button to span?
Also, instead of adding onclick to anchor tag, should we change it to a button?

2024-01-16 00:30 UTC, MySmilingTurban commented on src/utils/gamePlay.ts
> +type User = {
move all types and interfaces to a single file/folder

2024-01-16 23:32 UTC, amitojsingh commented on src/utils/gamePlay.ts
> +type User = {
fixed

2024-01-16 23:33 UTC, amitojsingh commented on src/components/buttons/StartQuestionBtn.tsx
>        <button
fixed

2024-01-16 23:33 UTC, amitojsingh commented on src/store/features/currentGamePositionSlice.ts
> +const currentGamePositionSlice = createSlice({
fixed

2024-01-17 02:16 UTC, MySmilingTurban approved these changes
looks good to me!

2024-01-17 03:10 UTC, merged