Added User profile page
KhalisFoundation/gurmukhi-web pull request #73
Opened 2024-01-21 04:17 UTC by MySmilingTurban

2024-01-22 19:44 UTC, amitojsingh commented
@MySmilingTurban veer ji can we add a thumbnail for profile pic when we upload? Also can we move all the content to center with a transparent box as our web app is more centric. Also can we make button (Verify/save/upload/choose file) design similar to start button just for the consistency.

2024-01-23 00:49 UTC, MySmilingTurban commented
Fixed as per suggestions

<img width="1728" alt="Screenshot 2024-01-23 at 11 39 52 am" src="https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/1c39b55f-c34f-4867-8919-52b460e2189d">

<img width="1728" alt="Screenshot 2024-01-23 at 11 40 12 am" src="https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/c773d975-2093-4a05-9766-7f9ff24f007d">


https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/e4ca3a1d-a4a8-4307-a6bf-b7bac12a3e47

cc: @amitojsingh

2024-01-23 01:22 UTC, amitojsingh commented
@MySmilingTurban can you check why deploy is failing?

2024-01-23 01:35 UTC, MySmilingTurban commented
> @MySmilingTurban can you check why deploy is failing?

fixed

2024-01-23 03:32 UTC, amitojsingh requested changes

2024-01-23 03:32 UTC, amitojsingh commented on src/pages/dashboard/components/wordBox/index.tsx
>    }, []);
please add user in the useEffect dependency

2024-01-23 04:36 UTC, MySmilingTurban commented on src/pages/dashboard/components/wordBox/index.tsx
>    }, []);
fixed

2024-01-25 01:55 UTC, amitojsingh commented
@MySmilingTurban veer ji can you add a full page loading or some animation? I can see a small loader once we save. Also, make it reusable so that we can use it in our entire app where ever loading is required.

2024-01-26 17:32 UTC, amitojsingh approved these changes

2024-01-26 17:33 UTC, amitojsingh commented
For Loading we can create new task. Let's resolve conflicts and merge. 
Looks good to me. Great Work Veer ji. 
@MySmilingTurban

2024-01-26 18:50 UTC, merged