feat: narakeet integration
KhalisFoundation/gurmukhi-web pull request #78
Opened 2024-01-24 04:43 UTC by MySmilingTurban

2024-02-01 22:40 UTC, amitojsingh commented
@MySmilingTurban Veer ji can we host this on firebase?

2024-02-01 23:12 UTC, amitojsingh requested changes

2024-02-01 23:12 UTC, amitojsingh commented on src/utils/textToSpeech.ts
> +  const request: protos.google.cloud.texttospeech.v1.ISynthesizeSpeechRequest = {
I think we don't need google text to speech we can remove this file.

2024-02-01 23:12 UTC, amitojsingh commented on tsconfig.json
> +    "noImplicitAny": false,
why we made implicitAny false?

2024-02-02 04:22 UTC, MySmilingTurban commented on src/components/buttons/TextToSpeechBtn.tsx
> +  text?: string;
hnji, fixed

2024-02-02 04:23 UTC, MySmilingTurban commented on src/components/buttons/TextToSpeechBtn.tsx
> +  const [isLoading, setIsLoading] = useState(false);
fixed

2024-02-02 04:23 UTC, MySmilingTurban commented on src/components/questions/multiple-choice.tsx
> +        <TextToSpeechBtn backgroundColor='bg-white-175' text={question.question} />
sure, fixed

2024-02-02 04:23 UTC, MySmilingTurban commented on src/utils/textToSpeech.ts
> +  const request: protos.google.cloud.texttospeech.v1.ISynthesizeSpeechRequest = {
done

2024-02-02 18:35 UTC, amitojsingh commented
@MySmilingTurban veer ji can we host this to firebase?

2024-02-03 00:51 UTC, MySmilingTurban commented
> @MySmilingTurban veer ji can we host this to firebase?

Hnji, I am working on it
Looking into firebase functions for this

2024-02-03 00:57 UTC, MySmilingTurban commented
@amitojsingh veerji, should we merge this?
as the code will remain the same, we'll only have to change the env var for backend API URL

2024-02-03 04:37 UTC, amitojsingh approved these changes

2024-02-07 01:19 UTC, amitojsingh requested changes

2024-02-07 01:19 UTC, amitojsingh commented on package.json
> +    "@google-cloud/text-to-speech": "^5.0.2",
I think we can remove this.

2024-02-07 01:19 UTC, amitojsingh commented on src/components/buttons/TextToSpeechBtn.tsx
> +        console.error('Error generating audio:', error);
we need to implement Firebase crashlytics to view any error. console is not a good practice. we can create a separate PR/ Task for this.

2024-02-07 01:19 UTC, amitojsingh commented on src/components/buttons/TextToSpeechBtn.tsx
> +        <svg
can we use loaderComponent here?

2024-02-07 01:30 UTC, MySmilingTurban commented on src/components/buttons/TextToSpeechBtn.tsx
> +        console.error('Error generating audio:', error);
created new issue for this

2024-02-09 15:04 UTC, MySmilingTurban commented on package.json
> +    "@google-cloud/text-to-speech": "^5.0.2",
fixed

2024-02-09 15:04 UTC, MySmilingTurban commented on src/components/buttons/TextToSpeechBtn.tsx
> +        <svg
sure, fixed

2024-02-10 14:27 UTC, amitojsingh approved these changes

2024-02-10 21:32 UTC, merged