fix: login designing
KhalisFoundation/gurmukhi-web pull request #80
Opened 2024-01-30 21:46 UTC by amitojsingh

2024-01-31 21:40 UTC, MySmilingTurban requested changes

2024-01-31 21:40 UTC, MySmilingTurban commented on src/components/signin/SignIn.tsx
> -    <main className="flex bg-white h-full w-[45rem] rounded-3xl flex-col justify-center items-center py-20 px-32 gap-5 brandon-grotesque">
py-20 (or an alternative) is needed to keep the UI in tune with design.
There is expected to be equal padding both horizontally and vertically.

![login_form_ui](https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/6917814d-b3df-4942-b603-bb64c6437433)

2024-02-02 00:04 UTC, amitojsingh commented on src/components/signin/SignIn.tsx
> -    <main className="flex bg-white h-full w-[45rem] rounded-3xl flex-col justify-center items-center py-20 px-32 gap-5 brandon-grotesque">
Fixed Veer ji

2024-02-03 00:50 UTC, MySmilingTurban approved these changes
looks good to me!

2024-02-03 00:56 UTC, merged