fix: repeat algo on completion.
KhalisFoundation/gurmukhi-web pull request #83
Opened 2024-02-01 22:38 UTC by amitojsingh

Fixed #81

2024-02-02 04:17 UTC, MySmilingTurban requested changes

2024-02-02 04:17 UTC, MySmilingTurban commented on src/components/buttons/LoderButton.tsx
rename file to LoaderButton.tsx

2024-02-02 18:49 UTC, amitojsingh commented on src/components/buttons/LoderButton.tsx
fixed

2024-02-03 00:49 UTC, MySmilingTurban approved these changes

2024-02-03 00:49 UTC, merged