fix: improved the algorithm
KhalisFoundation/gurmukhi-web pull request #86
Opened 2024-02-09 05:14 UTC by amitojsingh

To Test Please create a new user.

2024-02-09 22:21 UTC, MySmilingTurban requested changes

2024-02-09 22:21 UTC, MySmilingTurban commented on src/pages/dashboard/hooks/useNew.ts
> +  const addWordIfNotExists = (word: WordType, learningWords:WordShabadavaliDB[]) => {
add empty between imports and functions
add adequate spaces for better formatting

2024-02-09 22:21 UTC, MySmilingTurban commented on src/pages/dashboard/hooks/useQuestions.ts
> +
nit: remove empty line

2024-02-10 14:58 UTC, amitojsingh commented on src/pages/dashboard/hooks/useNew.ts
> +  const addWordIfNotExists = (word: WordType, learningWords:WordShabadavaliDB[]) => {
fixed

2024-02-10 14:58 UTC, amitojsingh commented on src/pages/dashboard/hooks/useQuestions.ts
> +
fixed

2024-02-10 21:37 UTC, MySmilingTurban requested changes
also, resolve conflicts

2024-02-10 21:37 UTC, MySmilingTurban commented on src/pages/dashboard/hooks/useNew.ts
> +  const addWordIfNotExists = (word: WordType, learningWords:WordShabadavaliDB[]) => {
()=>{ should be () => {

2024-02-11 03:58 UTC, amitojsingh commented on src/pages/dashboard/hooks/useNew.ts
> +  const addWordIfNotExists = (word: WordType, learningWords:WordShabadavaliDB[]) => {
fixed

2024-02-11 11:02 UTC, MySmilingTurban approved these changes
looks good to me!
left a comment about removal of back button in words layout page.

2024-02-11 11:02 UTC, MySmilingTurban commented on src/pages/word/layout.tsx
@amitojsingh veerji, this was intentionally added only for word pages to allow users to navigate back and forth through word information.

2024-02-12 06:11 UTC, MySmilingTurban commented
@amitojsingh , should we push this to dev?

2024-02-12 06:17 UTC, amitojsingh commented
Nopes, Veer Ji I tested this. This is also stuck. Because I merge dev branch here. 
We need to first fix the dev branch and then we can merge this.

2024-02-16 20:46 UTC, MySmilingTurban approved these changes
Looks good to me!

2024-02-16 23:04 UTC, merged