Fix font issue on all browsers
KhalisFoundation/gurmukhi-web pull request #93
Opened 2024-02-16 07:06 UTC by MySmilingTurban

2024-02-16 20:39 UTC, amitojsingh requested changes

2024-02-16 20:39 UTC, amitojsingh commented on functions/index.js
> +require('dotenv').config();
looks good veer ji. are we going to deploy this from functions folder? is it auto-depoloyed everytime we push the code?

2024-02-16 23:15 UTC, MySmilingTurban commented on functions/index.js
> +require('dotenv').config();
functions folder is separately deployed from another repo
removed it and added it to .gitignore

2024-02-17 02:26 UTC, amitojsingh approved these changes

2024-02-17 03:53 UTC, merged