Improve algo
KhalisFoundation/gurmukhi-web pull request #95
Opened 2024-02-16 23:05 UTC by amitojsingh

2024-02-16 23:18 UTC, MySmilingTurban commented
Please add description and fix deployment issues
@amitojsingh

2024-02-16 23:24 UTC, MySmilingTurban commented
Can we also add Back button in this or in another PR?

2024-02-16 23:26 UTC, amitojsingh commented
done @MySmilingTurban can you check now?

2024-02-17 00:41 UTC, MySmilingTurban requested changes
One minor change

2024-02-17 00:41 UTC, MySmilingTurban commented on src/pages/dashboard/hooks/useGamePlay1.ts
> +    const usr = await getUserData(user.uid);
rename it to userData?

2024-02-17 00:44 UTC, amitojsingh commented on src/pages/dashboard/hooks/useGamePlay1.ts
> +    const usr = await getUserData(user.uid);
fixed

2024-02-17 00:47 UTC, merged