feat: optimise initial gameSession with locally stored headstart
KhalisFoundation/gurmukhi-web pull request #97
Opened 2024-02-18 12:01 UTC by MySmilingTurban

This PR allows the web app to initiate the gamePlay using locally stored gameSession for first run which eliminates the 30+ seconds fetching.

2024-02-19 20:05 UTC, amitojsingh commented
@MySmilingTurban Veer ji there is a bug in the WinCoin page when all the questions are completed. Can you check? 
1. Nanak coin is not updating. 
2. Get One More question is not working.

2024-02-20 03:02 UTC, amitojsingh requested changes

2024-02-20 03:02 UTC, amitojsingh commented on src/constants/gameSession0.ts
> +  {
Veer ji can we create a data/seed0.json file and include all data and fetch data from json file instead of constant file.

2024-02-22 23:49 UTC, MySmilingTurban commented
> @MySmilingTurban Veer ji there is a bug in the WinCoin page when all the questions are completed. Can you check?
> 
> 1. Nanak coin is not updating.
> 2. Get One More question is not working.

Fixed
cc: @amitojsingh

2024-02-23 02:39 UTC, amitojsingh approved these changes

2024-02-23 02:39 UTC, merged